BEGIN
  FOR reg IN (SELECT NR_CARGA, DS_CARGA, QT_TOTAL, QT_GRAVADO, NR_CARGA_PAI, CD_SITUACAO_PROCESSO
                FROM SYSTUR.GEN_CARGA_BACKGROUND
               WHERE CD_SISTEMA  = 6 
                 AND ( NVL(QT_TOTAL,1) <> NVL(QT_GRAVADO,1) OR CD_SITUACAO_PROCESSO = 'P')       
                 AND NR_CARGA_PAI IN (SELECT DISTINCT NR_CARGA_PAI
                                        FROM SYSTUR.GEN_CARGA_BACKGROUND
                                       WHERE CD_SISTEMA = 6
                                         AND CD_SITUACAO_PROCESSO IN ('P')
                                         AND DT_ATUALIZACAO <= TRUNC(SYSDATE)
                                      )
               ORDER BY NR_CARGA_PAI, NR_CARGA) LOOP
    IF (reg.CD_SITUACAO_PROCESSO = 'P' AND reg.QT_TOTAL IS NULL) THEN
      UPDATE SYSTUR.GEN_CARGA_BACKGROUND SET CD_SITUACAO_PROCESSO = 'C' WHERE NR_CARGA = reg.NR_CARGA AND CD_SISTEMA = 6;
    ELSIF (reg.CD_SITUACAO_PROCESSO = 'P' AND reg.QT_TOTAL IS NOT NULL) THEN
      UPDATE SYSTUR.GEN_CARGA_BACKGROUND SET CD_SITUACAO_PROCESSO = 'C', QT_GRAVADO=QT_TOTAL WHERE NR_CARGA = reg.NR_CARGA AND CD_SISTEMA = 6;
    ELSIF (reg.CD_SITUACAO_PROCESSO = 'C') THEN      
      UPDATE SYSTUR.GEN_CARGA_BACKGROUND SET QT_GRAVADO=QT_TOTAL WHERE NR_CARGA = reg.NR_CARGA AND CD_SISTEMA = 6;
    END IF;
  END LOOP;
END;
/
